INSERT INTO zamówienie VALUES ('1','20-10-12');
INSERT INTO zamówienie VALUES ('2','20-08-02');
INSERT INTO zamówienie VALUES ('3','20-11-11');
INSERT INTO zamówienie VALUES ('4','20-05-25');
INSERT INTO zamówienie VALUES ('5','20-04-03');
INSERT INTO zamówienie VALUES ('6','20-03-26');
INSERT INTO zamówienie VALUES ('7','20-03-15');
INSERT INTO zamówienie VALUES ('8','20-07-13');
INSERT INTO zamówienie VALUES ('9','20-06-03');
INSERT INTO zamówienie VALUES ('10','20-02-04');

INSERT INTO czytelnicy VALUES ('1','Janusz', 'Kowal');
INSERT INTO czytelnicy VALUES ('2','Maria', 'Chrzan');
INSERT INTO czytelnicy VALUES ('3','Mariusz', 'Chrzanowski');
INSERT INTO czytelnicy VALUES ('4','Dariusz', 'Krysiński');
INSERT INTO czytelnicy VALUES ('5','Wojciech', 'Rębowski');
INSERT INTO czytelnicy VALUES ('6','Marcel', 'Dębowski');
INSERT INTO czytelnicy VALUES ('7','Aleksandra', 'Wryta');
INSERT INTO czytelnicy VALUES ('8','Kamil', 'Bruzd');
INSERT INTO czytelnicy VALUES ('9','Wiesława', 'Najda');
INSERT INTO czytelnicy VALUES ('10','Kamila', 'Bosak');

INSERT INTO książka VALUES ('1','Ferdydurka');
INSERT INTO książka VALUES ('2','Dziady');
INSERT INTO książka VALUES ('3','Harry Potter');
INSERT INTO książka VALUES ('4','Zmierzch');
INSERT INTO książka VALUES ('5','Hobbit');
INSERT INTO książka VALUES ('6','Potop');
INSERT INTO książka VALUES ('7','Wesele');
INSERT INTO książka VALUES ('8','Chłopi');
INSERT INTO książka VALUES ('9','Tango');
INSERT INTO książka VALUES ('10','Diuna');

INSERT INTO autor VALUES ('1', 'Witold', 'Gombrowicz' );
INSERT INTO autor VALUES ('2', 'Adam', 'Mickiewicz' );
INSERT INTO autor VALUES ('3', 'J.K', 'Rowling' );
INSERT INTO autor VALUES ('4', 'Stephenie', 'Meyer');
INSERT INTO autor VALUES ('5', 'John', 'Tolkien');
INSERT INTO autor VALUES ('6', 'Henryk', 'Sienkiewicz');
INSERT INTO autor VALUES ('7', 'Stanisław', 'Wyspiański');
INSERT INTO autor VALUES ('8', 'Władysław', 'Rejmont');
INSERT INTO autor VALUES ('9', 'Sławomir', 'Mrożek');
INSERT INTO autor VALUES ('10', 'Frank', 'Herbert');